export const IS_AUTHENTICATED = 'IS_AUTHENTICATED';
export const SET_USER = 'SET_USER';

export const IS_NEW_USER = 'IS_NEW_USER';

export const SET_MALE_MUSIC_LIST = 'SET_MALE_MUSIC_LIST';
export const SET_FEMALE_MUSIC_LIST = 'SET_FEMALE_MUSIC_LIST';

export const RESET_MALE_MUSIC_LIST = 'RESET_MALE_MUSIC_LIST';
export const RESET_FEMALE_MUSIC_LIST = 'RESET_FEMALE_MUSIC_LIST';

export const SET_MALE_MUSIC_LIST_LOADING = 'SET_MALE_MUSIC_LIST_LOADING';
export const SET_FEMALE_MUSIC_LIST_LOADING = 'SET_FEMALE_MUSIC_LIST_LOADING';

export const SET_MEDITATE_MUSIC_LIST = 'SET_MEDITATE_MUSIC_LIST';
export const SET_ACTIVE_SONG_ID = 'SET_ACTIVE_SONG_ID';
export const SET_ACTIVE_SONG_DATA = 'SET_ACTIVE_SONG_DATA';
export const RESET_ACTIVE_SONG_ID = 'RESET_ACTIVE_SONG_ID';
